"""switch voice embeddings to pretrained speaker embeddings

Revision ID: bc6572c6f0d8
Revises: fd26d9d1b9fb
Create Date: 2026-08-14 17:29:20.114710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6572c6f0d8'
down_revision = 'fd26d9d1b9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_json', sa.Text(), nullable=False))
        batch_op.drop_column('rms_energy')
        batch_op.drop_column('duration')
        batch_op.drop_column('spectral_spread')
        batch_op.drop_column('zcr')
        batch_op.drop_column('spectral_centroid')
        batch_op.drop_column('spectral_rolloff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spectral_rolloff', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('spectral_centroid', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('zcr', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('spectral_spread', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('rms_energy', sa.FLOAT(), nullable=True))
        batch_op.drop_column('embedding_json')

    # ### end Alembic commands ###
