"""add voice recognition logs for replay detection

Revision ID: cf47691b6bae
Revises: d2678b5102b7
Create Date: 2026-08-14 17:50:45.347643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf47691b6bae'
down_revision = 'd2678b5102b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_recognition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_hash', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_recognition_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_recognition_logs_audio_hash'), ['audio_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_recognition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_recognition_logs_audio_hash'))

    op.drop_table('voice_recognition_logs')
    # ### end Alembic commands ###
